-- -- set termguicolors to enable highlight groups
--
-- vim.keymap.set("n", '<leader>ot', vim.cmd.NvimTreeFindFileToggle)
--
-- -- OR setup with some options
-- require("nvim-tree").setup({
--   sort_by = "case_sensitive",
--   renderer = {
--     group_empty = true,
--   },
--   filters = {
--     dotfiles = true,
--   },
-- })
